# -*- coding: utf-8 -*-
"""ECC-Algorithm-team.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fySoB5lbc5sb5QXZHYo7tz-Rl_KY_7vg
"""
#Week5
#1676번

def fact(n) :
    value = 1
    if (n != 1) : 
        for i in range (2, n+1, 1) :
            value *= i 
    return value

N = int(input())

msg = str(fact(N))
cnt = 0

for i in range (len(msg)-1, -1, -1):
    if ( msg[i] == '0' ):
        cnt += 1
    else:
        break

print(cnt)

# 1978번 소수 찾기

N = int(input())
nlist = list(map(int, input().split(" ")))

cnt = 0

for i in range (0, N, 1) :
    if (nlist[i] == 1) :
        continue
    if (nlist[i] == 2) :
        cnt = cnt + 1
        continue

    for j in range (2, nlist[i], 1) :
        if (nlist[i] % j == 0) :
            break
        if (j == nlist[i] - 1) :
            cnt = cnt + 1
            
print(cnt)


#1373번

n = int(input(), 2)
k = str(oct(n))

print(k[2:])
