# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k_KtKBOV29dpgmmcgAd8Eqw-xT3GneWx
"""

# 10주차 6603번
from itertools import combinations
    
while True :
    n_list = list(map(int, input().split()))
    if n_list[0] == 0 :
        break
    n = n_list[0]
    num_list = n_list[1:]
    c = list(combinations(num_list,6))
    for i in range(len(c)) :
        for j in range(6) :
            print(str(c[i][j]), end = ' ')
        print()
    print()


# 10주차 1182번
from itertools import combinations

n, s = map(int, input().split(" "))
n_list = list(map(int, input().split(" ")))

cnt = 0

for i in range(1, n+1, 1):
    c = combinations(n_list,i)
    for j in list(c) :
        if (sum(j) == s ):
            cnt += 1
            
print(cnt)